FROM python:3.14-slim

WORKDIR /app

COPY requirements.txt .

RUN python -m venv .venv && . .venv/bin/activate && pip install --upgrade pip && pip install -r requirements.txt

COPY . .

ENV PATH="/app/.venv/bin:$PATH"
ENV OLLAMA_HOST="http://ollama:11434"

CMD ["daphne", "backend.asgi:application", "-e", "ssl:443:privateKey=ssl/localhost+2-key.pem:certKey=ssl/localhost+2.pem"]