FROM python:3.14-slim

WORKDIR /app

COPY requirements.txt .

RUN python -m venv .venv && . .venv/bin/activate && pip install --upgrade pip && pip install -r requirements.txt

ENV PATH="/app/.venv/bin:$PATH"

COPY . .