# Generated by Django 5.2.4 on 2025-08-07 19:43

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_chat_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to="chat_files/")),
                ("name", models.TextField()),
                ("message", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="files", to="chat.message")),
            ],
        ),
    ]