FROM python:3.14-slim

WORKDIR /app/backend

COPY /backend/requirements.txt .

RUN python -m venv .venv && . .venv/bin/activate && pip install --upgrade pip && pip install -r requirements.txt

ENV PATH="/app/backend/.venv/bin:$PATH"

COPY /backend .

WORKDIR /app/frontend

RUN apt-get update && \
    apt-get install -y wget xz-utils && \
    rm -rf /var/lib/apt/lists/* && \
    mkdir -p /app_deps && \
    wget -O /app_deps/node-v24.11.0-linux-x64.tar.xz https://nodejs.org/dist/v24.11.0/node-v24.11.0-linux-x64.tar.xz && \
    tar -xf /app_deps/node-v24.11.0-linux-x64.tar.xz -C /app_deps && \
    rm /app_deps/node-v24.11.0-linux-x64.tar.xz

ENV PATH="/app_deps/node-v24.11.0-linux-x64/bin:$PATH"

COPY /frontend/package.json /frontend/package-lock.json ./

RUN npm install

COPY /frontend .